# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ContactPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'number': 'str',
        'email': 'str',
        'groups': 'list[int]'
    }

    attribute_map = {
        'name': 'name',
        'number': 'number',
        'email': 'email',
        'groups': 'groups'
    }

    def __init__(self, name=None, number=None, email=None, groups=None):  # noqa: E501
        """ContactPayload - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._number = None
        self._email = None
        self._groups = None
        self.discriminator = None
        self.name = name
        if number is not None:
            self.number = number
        if email is not None:
            self.email = email
        if groups is not None:
            self.groups = groups

    @property
    def name(self):
        """Gets the name of this ContactPayload.  # noqa: E501

        The contact's full name  # noqa: E501

        :return: The name of this ContactPayload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContactPayload.

        The contact's full name  # noqa: E501

        :param name: The name of this ContactPayload.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def number(self):
        """Gets the number of this ContactPayload.  # noqa: E501

        The contact's phonenumber  # noqa: E501

        :return: The number of this ContactPayload.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this ContactPayload.

        The contact's phonenumber  # noqa: E501

        :param number: The number of this ContactPayload.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def email(self):
        """Gets the email of this ContactPayload.  # noqa: E501

        The contact's email  # noqa: E501

        :return: The email of this ContactPayload.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this ContactPayload.

        The contact's email  # noqa: E501

        :param email: The email of this ContactPayload.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def groups(self):
        """Gets the groups of this ContactPayload.  # noqa: E501

        a list of group ids to attach this contact to  # noqa: E501

        :return: The groups of this ContactPayload.  # noqa: E501
        :rtype: list[int]
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this ContactPayload.

        a list of group ids to attach this contact to  # noqa: E501

        :param groups: The groups of this ContactPayload.  # noqa: E501
        :type: list[int]
        """

        self._groups = groups

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ContactPayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
