# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessagePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'recipients': 'list[MessagePayloadRecipients]',
        'text': 'str',
        'provider': 'str',
        'type': 'str'
    }

    attribute_map = {
        'recipients': 'recipients',
        'text': 'text',
        'provider': 'provider',
        'type': 'type'
    }

    def __init__(self, recipients=None, text=None, provider='sms', type='default'):  # noqa: E501
        """MessagePayload - a model defined in Swagger"""  # noqa: E501
        self._recipients = None
        self._text = None
        self._provider = None
        self._type = None
        self.discriminator = None
        self.recipients = recipients
        self.text = text
        if provider is not None:
            self.provider = provider
        if type is not None:
            self.type = type

    @property
    def recipients(self):
        """Gets the recipients of this MessagePayload.  # noqa: E501

        An array of recipients  # noqa: E501

        :return: The recipients of this MessagePayload.  # noqa: E501
        :rtype: list[MessagePayloadRecipients]
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """Sets the recipients of this MessagePayload.

        An array of recipients  # noqa: E501

        :param recipients: The recipients of this MessagePayload.  # noqa: E501
        :type: list[MessagePayloadRecipients]
        """
        if recipients is None:
            raise ValueError("Invalid value for `recipients`, must not be `None`")  # noqa: E501

        self._recipients = recipients

    @property
    def text(self):
        """Gets the text of this MessagePayload.  # noqa: E501

        Content of the text message  # noqa: E501

        :return: The text of this MessagePayload.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this MessagePayload.

        Content of the text message  # noqa: E501

        :param text: The text of this MessagePayload.  # noqa: E501
        :type: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def provider(self):
        """Gets the provider of this MessagePayload.  # noqa: E501

        The name of the provider  # noqa: E501

        :return: The provider of this MessagePayload.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this MessagePayload.

        The name of the provider  # noqa: E501

        :param provider: The provider of this MessagePayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["sms", "telegram"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def type(self):
        """Gets the type of this MessagePayload.  # noqa: E501

        Describes the type of the message: <br><br> 1. `default: ` Use the default configured type<br><br> 2. `flash:` <b>`ONLY WHEN THE SMS PROVIDER IS USED`<b> When true, the message appears directly on the recipient's phone display and it is not stored when dismissed. Most phones support this feature, but not all. Flash messages are useful during emergency situations <br><br> 3. `ring:` <b>`ONLY WHEN THE SMS PROVIDER IS USED`<b> When true then instead of sending an SMS, a voice call will be made to the recipient's phone number but when the recipient picks up the call nothing will be heard. Note that voice calls might not be supported by your unit's modem. Ring messages are useful during emergency situations.<br>  Note that even if you choose the `ring` type you will need to provide a text with at least one character.   # noqa: E501

        :return: The type of this MessagePayload.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MessagePayload.

        Describes the type of the message: <br><br> 1. `default: ` Use the default configured type<br><br> 2. `flash:` <b>`ONLY WHEN THE SMS PROVIDER IS USED`<b> When true, the message appears directly on the recipient's phone display and it is not stored when dismissed. Most phones support this feature, but not all. Flash messages are useful during emergency situations <br><br> 3. `ring:` <b>`ONLY WHEN THE SMS PROVIDER IS USED`<b> When true then instead of sending an SMS, a voice call will be made to the recipient's phone number but when the recipient picks up the call nothing will be heard. Note that voice calls might not be supported by your unit's modem. Ring messages are useful during emergency situations.<br>  Note that even if you choose the `ring` type you will need to provide a text with at least one character.   # noqa: E501

        :param type: The type of this MessagePayload.  # noqa: E501
        :type: str
        """
        allowed_values = ["default", "flash", "ring"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
