# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Message(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'text': 'str',
        'provider': 'str',
        'timestamp': 'str',
        'is_flash': 'bool',
        'is_ring': 'bool',
        'senders': 'list[Contact]',
        'recipients': 'list[Contact]'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'text': 'text',
        'provider': 'provider',
        'timestamp': 'timestamp',
        'is_flash': 'isFlash',
        'is_ring': 'isRing',
        'senders': 'senders',
        'recipients': 'recipients'
    }

    def __init__(self, id=None, type=None, text=None, provider=None, timestamp=None, is_flash=None, is_ring=None, senders=None, recipients=None):  # noqa: E501
        """Message - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._type = None
        self._text = None
        self._provider = None
        self._timestamp = None
        self._is_flash = None
        self._is_ring = None
        self._senders = None
        self._recipients = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if text is not None:
            self.text = text
        if provider is not None:
            self.provider = provider
        if timestamp is not None:
            self.timestamp = timestamp
        if is_flash is not None:
            self.is_flash = is_flash
        if is_ring is not None:
            self.is_ring = is_ring
        if senders is not None:
            self.senders = senders
        if recipients is not None:
            self.recipients = recipients

    @property
    def id(self):
        """Gets the id of this Message.  # noqa: E501

        The message's id  # noqa: E501

        :return: The id of this Message.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Message.

        The message's id  # noqa: E501

        :param id: The id of this Message.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this Message.  # noqa: E501

        The type / status of the message:   <br><br>1. `sent :` The message is sent       <br>2. `failed:` The message failed to be sent       <br>3. `queued:` The message is in the \"to be sent\" queue       <br>4. `incoming:` The message is received   # noqa: E501

        :return: The type of this Message.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Message.

        The type / status of the message:   <br><br>1. `sent :` The message is sent       <br>2. `failed:` The message failed to be sent       <br>3. `queued:` The message is in the \"to be sent\" queue       <br>4. `incoming:` The message is received   # noqa: E501

        :param type: The type of this Message.  # noqa: E501
        :type: str
        """
        allowed_values = ["sent", "incoming", "failed", "queued"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def text(self):
        """Gets the text of this Message.  # noqa: E501

        The message's text  # noqa: E501

        :return: The text of this Message.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Message.

        The message's text  # noqa: E501

        :param text: The text of this Message.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def provider(self):
        """Gets the provider of this Message.  # noqa: E501

        The message's provider:   <br><br>1. `sms :` The message is a sms message       <br>2. `telegram:` The message is a telegram message   # noqa: E501

        :return: The provider of this Message.  # noqa: E501
        :rtype: str
        """
        return self._provider

    @provider.setter
    def provider(self, provider):
        """Sets the provider of this Message.

        The message's provider:   <br><br>1. `sms :` The message is a sms message       <br>2. `telegram:` The message is a telegram message   # noqa: E501

        :param provider: The provider of this Message.  # noqa: E501
        :type: str
        """
        allowed_values = ["sms", "telegram"]  # noqa: E501
        if provider not in allowed_values:
            raise ValueError(
                "Invalid value for `provider` ({0}), must be one of {1}"  # noqa: E501
                .format(provider, allowed_values)
            )

        self._provider = provider

    @property
    def timestamp(self):
        """Gets the timestamp of this Message.  # noqa: E501

        The message's timestamp  # noqa: E501

        :return: The timestamp of this Message.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this Message.

        The message's timestamp  # noqa: E501

        :param timestamp: The timestamp of this Message.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def is_flash(self):
        """Gets the is_flash of this Message.  # noqa: E501

        True when the message is a flash message  # noqa: E501

        :return: The is_flash of this Message.  # noqa: E501
        :rtype: bool
        """
        return self._is_flash

    @is_flash.setter
    def is_flash(self, is_flash):
        """Sets the is_flash of this Message.

        True when the message is a flash message  # noqa: E501

        :param is_flash: The is_flash of this Message.  # noqa: E501
        :type: bool
        """

        self._is_flash = is_flash

    @property
    def is_ring(self):
        """Gets the is_ring of this Message.  # noqa: E501

        True when the message is a ring message  # noqa: E501

        :return: The is_ring of this Message.  # noqa: E501
        :rtype: bool
        """
        return self._is_ring

    @is_ring.setter
    def is_ring(self, is_ring):
        """Sets the is_ring of this Message.

        True when the message is a ring message  # noqa: E501

        :param is_ring: The is_ring of this Message.  # noqa: E501
        :type: bool
        """

        self._is_ring = is_ring

    @property
    def senders(self):
        """Gets the senders of this Message.  # noqa: E501


        :return: The senders of this Message.  # noqa: E501
        :rtype: list[Contact]
        """
        return self._senders

    @senders.setter
    def senders(self, senders):
        """Sets the senders of this Message.


        :param senders: The senders of this Message.  # noqa: E501
        :type: list[Contact]
        """

        self._senders = senders

    @property
    def recipients(self):
        """Gets the recipients of this Message.  # noqa: E501

        The contact entries of the message  # noqa: E501

        :return: The recipients of this Message.  # noqa: E501
        :rtype: list[Contact]
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """Sets the recipients of this Message.

        The contact entries of the message  # noqa: E501

        :param recipients: The recipients of this Message.  # noqa: E501
        :type: list[Contact]
        """

        self._recipients = recipients

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Message, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Message):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
