# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessagePayloadRecipients(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'to': 'str',
        'target': 'str'
    }

    attribute_map = {
        'to': 'to',
        'target': 'target'
    }

    def __init__(self, to=None, target='number'):  # noqa: E501
        """MessagePayloadRecipients - a model defined in Swagger"""  # noqa: E501
        self._to = None
        self._target = None
        self.discriminator = None
        self.to = to
        self.target = target

    @property
    def to(self):
        """Gets the to of this MessagePayloadRecipients.  # noqa: E501

        Recipient of the text message depending on target  # noqa: E501

        :return: The to of this MessagePayloadRecipients.  # noqa: E501
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """Sets the to of this MessagePayloadRecipients.

        Recipient of the text message depending on target  # noqa: E501

        :param to: The to of this MessagePayloadRecipients.  # noqa: E501
        :type: str
        """
        if to is None:
            raise ValueError("Invalid value for `to`, must not be `None`")  # noqa: E501

        self._to = to

    @property
    def target(self):
        """Gets the target of this MessagePayloadRecipients.  # noqa: E501

        describes the meaning of \"To\" value: <br><br>1. `number:` To = Recipient’s telephone number      <br>2. `contact:` To =  Contact's username or id      <br>3. `contactgroup:` To = Group name or id   # noqa: E501

        :return: The target of this MessagePayloadRecipients.  # noqa: E501
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this MessagePayloadRecipients.

        describes the meaning of \"To\" value: <br><br>1. `number:` To = Recipient’s telephone number      <br>2. `contact:` To =  Contact's username or id      <br>3. `contactgroup:` To = Group name or id   # noqa: E501

        :param target: The target of this MessagePayloadRecipients.  # noqa: E501
        :type: str
        """
        if target is None:
            raise ValueError("Invalid value for `target`, must not be `None`")  # noqa: E501
        allowed_values = ["number", "contact", "contactgroup"]  # noqa: E501
        if target not in allowed_values:
            raise ValueError(
                "Invalid value for `target` ({0}), must be one of {1}"  # noqa: E501
                .format(target, allowed_values)
            )

        self._target = target

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessagePayloadRecipients, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessagePayloadRecipients):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
