# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StateResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'iss': 'str',
        'host': 'str',
        'number': 'str',
        'unit': 'StateResponseUnit',
        'build': 'StateResponseBuild',
        'licenses': 'list[str]',
        'sim': 'StateResponseSim'
    }

    attribute_map = {
        'iss': 'iss',
        'host': 'host',
        'number': 'number',
        'unit': 'unit',
        'build': 'build',
        'licenses': 'licenses',
        'sim': 'sim'
    }

    def __init__(self, iss=None, host=None, number=None, unit=None, build=None, licenses=None, sim=None):  # noqa: E501
        """StateResponse - a model defined in Swagger"""  # noqa: E501
        self._iss = None
        self._host = None
        self._number = None
        self._unit = None
        self._build = None
        self._licenses = None
        self._sim = None
        self.discriminator = None
        if iss is not None:
            self.iss = iss
        if host is not None:
            self.host = host
        if number is not None:
            self.number = number
        if unit is not None:
            self.unit = unit
        if build is not None:
            self.build = build
        if licenses is not None:
            self.licenses = licenses
        if sim is not None:
            self.sim = sim

    @property
    def iss(self):
        """Gets the iss of this StateResponse.  # noqa: E501


        :return: The iss of this StateResponse.  # noqa: E501
        :rtype: str
        """
        return self._iss

    @iss.setter
    def iss(self, iss):
        """Sets the iss of this StateResponse.


        :param iss: The iss of this StateResponse.  # noqa: E501
        :type: str
        """

        self._iss = iss

    @property
    def host(self):
        """Gets the host of this StateResponse.  # noqa: E501


        :return: The host of this StateResponse.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this StateResponse.


        :param host: The host of this StateResponse.  # noqa: E501
        :type: str
        """

        self._host = host

    @property
    def number(self):
        """Gets the number of this StateResponse.  # noqa: E501


        :return: The number of this StateResponse.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this StateResponse.


        :param number: The number of this StateResponse.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def unit(self):
        """Gets the unit of this StateResponse.  # noqa: E501


        :return: The unit of this StateResponse.  # noqa: E501
        :rtype: StateResponseUnit
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this StateResponse.


        :param unit: The unit of this StateResponse.  # noqa: E501
        :type: StateResponseUnit
        """

        self._unit = unit

    @property
    def build(self):
        """Gets the build of this StateResponse.  # noqa: E501


        :return: The build of this StateResponse.  # noqa: E501
        :rtype: StateResponseBuild
        """
        return self._build

    @build.setter
    def build(self, build):
        """Sets the build of this StateResponse.


        :param build: The build of this StateResponse.  # noqa: E501
        :type: StateResponseBuild
        """

        self._build = build

    @property
    def licenses(self):
        """Gets the licenses of this StateResponse.  # noqa: E501


        :return: The licenses of this StateResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._licenses

    @licenses.setter
    def licenses(self, licenses):
        """Sets the licenses of this StateResponse.


        :param licenses: The licenses of this StateResponse.  # noqa: E501
        :type: list[str]
        """

        self._licenses = licenses

    @property
    def sim(self):
        """Gets the sim of this StateResponse.  # noqa: E501


        :return: The sim of this StateResponse.  # noqa: E501
        :rtype: StateResponseSim
        """
        return self._sim

    @sim.setter
    def sim(self, sim):
        """Sets the sim of this StateResponse.


        :param sim: The sim of this StateResponse.  # noqa: E501
        :type: StateResponseSim
        """

        self._sim = sim

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StateResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StateResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
