# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class StateResponseBuild(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'number': 'str',
        'branch': 'str',
        'commit': 'str',
        'time': 'str'
    }

    attribute_map = {
        'number': 'number',
        'branch': 'branch',
        'commit': 'commit',
        'time': 'time'
    }

    def __init__(self, number=None, branch=None, commit=None, time=None):  # noqa: E501
        """StateResponseBuild - a model defined in Swagger"""  # noqa: E501
        self._number = None
        self._branch = None
        self._commit = None
        self._time = None
        self.discriminator = None
        if number is not None:
            self.number = number
        if branch is not None:
            self.branch = branch
        if commit is not None:
            self.commit = commit
        if time is not None:
            self.time = time

    @property
    def number(self):
        """Gets the number of this StateResponseBuild.  # noqa: E501


        :return: The number of this StateResponseBuild.  # noqa: E501
        :rtype: str
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this StateResponseBuild.


        :param number: The number of this StateResponseBuild.  # noqa: E501
        :type: str
        """

        self._number = number

    @property
    def branch(self):
        """Gets the branch of this StateResponseBuild.  # noqa: E501


        :return: The branch of this StateResponseBuild.  # noqa: E501
        :rtype: str
        """
        return self._branch

    @branch.setter
    def branch(self, branch):
        """Sets the branch of this StateResponseBuild.


        :param branch: The branch of this StateResponseBuild.  # noqa: E501
        :type: str
        """

        self._branch = branch

    @property
    def commit(self):
        """Gets the commit of this StateResponseBuild.  # noqa: E501


        :return: The commit of this StateResponseBuild.  # noqa: E501
        :rtype: str
        """
        return self._commit

    @commit.setter
    def commit(self, commit):
        """Sets the commit of this StateResponseBuild.


        :param commit: The commit of this StateResponseBuild.  # noqa: E501
        :type: str
        """

        self._commit = commit

    @property
    def time(self):
        """Gets the time of this StateResponseBuild.  # noqa: E501


        :return: The time of this StateResponseBuild.  # noqa: E501
        :rtype: str
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this StateResponseBuild.


        :param time: The time of this StateResponseBuild.  # noqa: E501
        :type: str
        """

        self._time = time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StateResponseBuild, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StateResponseBuild):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
