# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TokenSigninResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'jwt': 'str',
        'expire_at': 'int'
    }

    attribute_map = {
        'jwt': 'jwt',
        'expire_at': 'expireAt'
    }

    def __init__(self, jwt=None, expire_at=None):  # noqa: E501
        """TokenSigninResponse - a model defined in Swagger"""  # noqa: E501
        self._jwt = None
        self._expire_at = None
        self.discriminator = None
        if jwt is not None:
            self.jwt = jwt
        if expire_at is not None:
            self.expire_at = expire_at

    @property
    def jwt(self):
        """Gets the jwt of this TokenSigninResponse.  # noqa: E501

        The JWT token. Decoding the JWT token will give more information about the user and its rights/permissions in the system  # noqa: E501

        :return: The jwt of this TokenSigninResponse.  # noqa: E501
        :rtype: str
        """
        return self._jwt

    @jwt.setter
    def jwt(self, jwt):
        """Sets the jwt of this TokenSigninResponse.

        The JWT token. Decoding the JWT token will give more information about the user and its rights/permissions in the system  # noqa: E501

        :param jwt: The jwt of this TokenSigninResponse.  # noqa: E501
        :type: str
        """

        self._jwt = jwt

    @property
    def expire_at(self):
        """Gets the expire_at of this TokenSigninResponse.  # noqa: E501

        The expiration unix timestamp  # noqa: E501

        :return: The expire_at of this TokenSigninResponse.  # noqa: E501
        :rtype: int
        """
        return self._expire_at

    @expire_at.setter
    def expire_at(self, expire_at):
        """Sets the expire_at of this TokenSigninResponse.

        The expiration unix timestamp  # noqa: E501

        :param expire_at: The expire_at of this TokenSigninResponse.  # noqa: E501
        :type: int
        """

        self._expire_at = expire_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TokenSigninResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenSigninResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
