# Generated by Django 5.2 on 2025-06-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_purpose',
            field=models.TextField(verbose_name='Purpose of Visit'),
        ),
    ]
