# Generated by Django 5.2 on 2025-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0002_alter_visitor_visit_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_purpose',
            field=models.CharField(max_length=1000),
        ),
    ]
