# Generated by Django 5.2 on 2025-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0003_alter_visitor_email_alter_visitor_visit_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_purpose',
            field=models.TextField(),
        ),
    ]
