# Generated by Django 5.2 on 2025-06-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0004_alter_visitor_email_alter_visitor_visit_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=50),
        ),
    ]
