# Generated by Django 5.2 on 2025-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0005_alter_visitor_visitor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='phone',
            new_name='host_phone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.AddField(
            model_name='visitor',
            name='factory',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
