# Generated by Django 5.2 on 2025-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0006_rename_phone_visitor_host_phone_remove_visitor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='email',
            field=models.EmailField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='first_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='last_name',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
