# Generated by Django 5.2 on 2025-06-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0007_adminprofile_email_adminprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='language',
            field=models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=2),
        ),
    ]
