# Generated by Django 5.2 on 2025-06-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0008_visitor_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='safety_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='factory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
