# Generated by Django 5.2 on 2025-06-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0009_visitor_safety_answers_alter_visitor_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='safety_answers',
        ),
        migrations.AddField(
            model_name='visitor',
            name='safety_question_1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='safety_question_2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
