# Generated by Django 5.2 on 2025-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0011_visitor_returned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
