# Generated by Django 5.2 on 2025-06-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0012_visitor_email_visitor_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_first_name', models.CharField(max_length=100)),
                ('visitor_last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('visit_purpose', models.TextField()),
                ('factory', models.BooleanField(default=False)),
                ('supervision', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('conference_needed', models.BooleanField(default=False)),
                ('conference_room', models.CharField(blank=True, choices=[('VIP', 'VIP'), ('Kreatywna', 'Kreatywna'), ('Kameralna', 'Kameralna')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GuestBook.reservation')),
            ],
        ),
    ]
