# Generated by Django 5.2 on 2025-07-09 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0013_adminprofile_phone_number_reservation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('visit_purpose', models.TextField()),
                ('host_name', models.CharField(max_length=100)),
                ('host_phone', models.CharField(max_length=20)),
                ('language', models.CharField(choices=[('pl', 'Polish'), ('en', 'English')], default='pl', max_length=2)),
                ('production_area', models.BooleanField(default=False)),
                ('with_supervision', models.BooleanField(default=False)),
                ('safety_acknowledged', models.BooleanField(default=True)),
                ('badge_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='known_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitor',
            name='safety_question_3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
