# Generated by Django 5.2 on 2025-07-09 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0014_trustedvisitor_remove_reservation_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='host_phone',
        ),
        migrations.AddField(
            model_name='visitor',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GuestBook.host'),
        ),
    ]
