# Generated by Django 5.2 on 2025-07-10 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0016_company_alter_visitor_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='audit_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='audit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='factory',
            field=models.ForeignKey(blank=True, default='Brak', null=True, on_delete=django.db.models.deletion.SET_NULL, to='GuestBook.company'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='with_supervision',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
