# Generated by Django 5.2 on 2025-07-11 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0017_visitor_audit_end_date_visitor_audit_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='visit_purpose',
        ),
        migrations.AddField(
            model_name='reservation',
            name='audit_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='audit_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GuestBook.host'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='other_purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='visit_purpose_choice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GuestBook.company'),
        ),
    ]
