# Generated by Django 5.2 on 2025-07-11 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0018_remove_reservation_visit_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor', to='GuestBook.reservation'),
        ),
    ]
