# Generated by Django 5.2 on 2025-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0019_visitor_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('sent', 'Reservation Sent'), ('arrived', 'Arrived'), ('completed', 'Visit Completed')], default='sent', max_length=20),
        ),
    ]
