# Generated by Django 5.2 on 2025-09-05 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0020_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivered at')),
                ('sender', models.CharField(max_length=120, verbose_name='Sender')),
                ('recipient', models.CharField(max_length=120, verbose_name='Recipient')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Code')),
                ('status', models.CharField(choices=[('in_box', 'W paczkomacie'), ('issued', 'Wydana')], default='in_box', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
