# Generated by Django 5.2.5 on 2025-09-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0021_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='company_name_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GuestBook.company'),
        ),
    ]
