# Generated by Django 5.2.5 on 2025-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0022_visitor_company_name_text_alter_visitor_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error'), ('timeout', 'Timeout'), ('no_number', 'No number')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='visitor',
            name='print_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error'), ('timeout', 'Timeout'), ('skipped', 'Skipped'), ('no_number', 'No number')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='visitor',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('error', 'Error'), ('timeout', 'Timeout'), ('skipped', 'Skipped'), ('no_number', 'No number')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='trustedvisitor',
            name='host_phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='trustedvisitor',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
