# Generated by Django 5.2.5 on 2025-09-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0023_reservation_sms_status_visitor_print_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='id_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('timeout', 'Timeout'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='print_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('timeout', 'Timeout'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='sms_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('timeout', 'Timeout'), ('error', 'Error'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
    ]
