# Generated by Django 5.2.5 on 2025-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0024_visitor_id_issued_alter_reservation_sms_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sms_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('sent', 'Sent'), ('timeout', 'Timeout'), ('error', 'Error'), ('no_number', 'No number'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=3),
        ),
    ]
