# Generated by Django 5.2.5 on 2025-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0025_alter_reservation_sms_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationcode',
            name='used',
        ),
        migrations.AddField(
            model_name='reservationcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reservationcode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
