# Generated by Django 5.2.5 on 2025-09-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0026_remove_reservationcode_used_reservationcode_max_uses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('sent', 'Reservation Sent'), ('arrived', 'Arrived'), ('completed', 'Visit Completed'), ('cancelled', 'Cancelled')], default='sent', max_length=20),
        ),
    ]
