# Generated by Django 5.2.5 on 2025-09-17 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestBook', '0027_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{1,3}$', 'ID musi mieć 1–3 cyfry.')]),
        ),
    ]
