# Generated by Django 5.2.14 on 2026-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GuestBook", "0031_package_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="KioskSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "printer_address",
                    models.CharField(default="10.30.40.150", max_length=200),
                ),
                ("printer_port", models.IntegerField(default=9100)),
            ],
            options={
                "verbose_name": "Kiosk Settings",
            },
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="printer_address",
            field=models.CharField(
                blank=True,
                default="10.30.40.150",
                max_length=200,
                verbose_name="Printer IP/hostname",
            ),
        ),
        migrations.AddField(
            model_name="adminprofile",
            name="printer_port",
            field=models.IntegerField(default=9100, verbose_name="Printer port"),
        ),
        migrations.AddField(
            model_name="host",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
