# Generated by Django 5.2.16 on 2026-07-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GuestBook", "0033_fix_visitor_id_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="label_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="Package number (from label)",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="label_photo",
            field=models.ImageField(blank=True, null=True, upload_to="package_labels/"),
        ),
        migrations.AddField(
            model_name="package",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="staff_comment",
            field=models.TextField(
                blank=True, default="", verbose_name="Reception comment"
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
