# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contacts_api import ContactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactsApi(unittest.TestCase):
    """ContactsApi unit test stubs"""

    def setUp(self):
        self.api = ContactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contacts_get(self):
        """Test case for contacts_get

        Get all contacts  # noqa: E501
        """
        pass

    def test_contacts_id_delete(self):
        """Test case for contacts_id_delete

        Delete a contact by its id  # noqa: E501
        """
        pass

    def test_contacts_id_get(self):
        """Test case for contacts_id_get

        Get a contact by its id  # noqa: E501
        """
        pass

    def test_contacts_id_post(self):
        """Test case for contacts_id_post

        Update a contact by its id  # noqa: E501
        """
        pass

    def test_contacts_post(self):
        """Test case for contacts_post

        Create a new contact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
