# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.state_response_unit import StateResponseUnit  # noqa: E501
from swagger_client.rest import ApiException


class TestStateResponseUnit(unittest.TestCase):
    """StateResponseUnit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStateResponseUnit(self):
        """Test StateResponseUnit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.state_response_unit.StateResponseUnit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
