# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.state_api import StateApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStateApi(unittest.TestCase):
    """StateApi unit test stubs"""

    def setUp(self):
        self.api = StateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_state_get(self):
        """Test case for state_get

        Get general information about the unit's build  # noqa: E501
        """
        pass

    def test_state_spec_json_get(self):
        """Test case for state_spec_json_get

        Get the Restful API specs as JSON  # noqa: E501
        """
        pass

    def test_state_spec_yml_get(self):
        """Test case for state_spec_yml_get

        Get the Restful API specs as yaml  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
