# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.messages_api import MessagesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self):
        self.api = MessagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_messages_get(self):
        """Test case for messages_get

        Get messages from the server  # noqa: E501
        """
        pass

    def test_messages_id_delete(self):
        """Test case for messages_id_delete

        Delete a message by its id  # noqa: E501
        """
        pass

    def test_messages_id_get(self):
        """Test case for messages_id_get

        Get a message by its id  # noqa: E501
        """
        pass

    def test_messages_post(self):
        """Test case for messages_post

        Send a message using one of the supported providers  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
