# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.contact_groups_api import ContactGroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContactGroupsApi(unittest.TestCase):
    """ContactGroupsApi unit test stubs"""

    def setUp(self):
        self.api = ContactGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contactgroups_get(self):
        """Test case for contactgroups_get

        Get all contact groups  # noqa: E501
        """
        pass

    def test_contactgroups_id_contacts_get(self):
        """Test case for contactgroups_id_contacts_get

        Get all contacts in the passed contact group  # noqa: E501
        """
        pass

    def test_contactgroups_id_delete(self):
        """Test case for contactgroups_id_delete

        Delete a contact group by its id  # noqa: E501
        """
        pass

    def test_contactgroups_id_get(self):
        """Test case for contactgroups_id_get

        Get a contact group by its id  # noqa: E501
        """
        pass

    def test_contactgroups_id_post(self):
        """Test case for contactgroups_id_post

        Update a contact group by its id  # noqa: E501
        """
        pass

    def test_contactgroups_post(self):
        """Test case for contactgroups_post

        Create a new contact group  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
