# coding: utf-8

"""
    brevis.one SMS Gateway API

    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501

    OpenAPI spec version: v23.01
    Contact: info@brevis.one
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="brevis.one SMS Gateway API",
    author_email="info@brevis.one",
    url="",
    keywords=["Swagger", "brevis.one SMS Gateway API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    brevis.one Restful API specifications to send/receive messages, manage contacts and groups.  # noqa: E501
    """
)
